### ISSUE TITLE
An error occure when apply the pwa extension

### ISSUE THREAD

**Issue by Roy-Kid** [askvortsov1/flarum-pwa#10]
I have successfully install pwa extension by composer require command
When I turn to barraar page and click the checkbox before the pwa item then:
![image](https://user-images.githubusercontent.com/42854324/93793608-9cc2d000-fc69-11ea-9046-b6a19ad28a4c.png)
I have updated all the things and reload the page but not work.
Should I install the sw.js and something else in the previous repo?

**Comment by askvortsov1** [comment]
Hi! Could you check your error logs (storage/logs/flarum) and share more info?

**Comment by Roy-Kid** [comment]
![image](https://user-images.githubusercontent.com/42854324/93880531-380e8080-fd10-11ea-9037-05a69da04428.png)
Thanks in advanced!

**Comment by askvortsov1** [comment]
Hi! It looks like this is cut off. Could you copy-paste the full log into a hastebin?

**Comment by Roy-Kid** [comment]
[flarum-2020-09-22.zip](https://github.com/askvortsov1/flarum-pwa/files/5261593/flarum-2020-09-22.zip)
SOOOO sorry for this mistake! Now i attach the log file in the compressed file

**Comment by askvortsov1** [comment]
Looks like it's trying to recreate a table that already exists. Try going into your database, dropping the `push_subscriptions` table, and then trying again

**Comment by Roy-Kid** [comment]
![image](https://user-images.githubusercontent.com/42854324/93897255-6f872800-fd24-11ea-9ec5-36514f25851f.png)
I delete it from `myphpadmin`, but still error at the extension store of flarum. Then I back to phpadmin and the push_subscriptions appears again. I attach the log. I...have almost no idea about the backend and I just use this beautiful framework for a BBS...
Hope you can help me !

**Comment by askvortsov1** [comment]
Ah, that is correct (no need to delete anything else). This is an issue with your database, take a look at https://discuss.flarum.org/d/23219-progressive-web-app-and-push-notifications/168

**Comment by Roy-Kid** [comment]
Thanks a lot ! Everything could work except one error when I install the extension for message pushing: 
![image](https://user-images.githubusercontent.com/42854324/93907607-20df8b00-fd30-11ea-936e-1dd75c6c8026.png)
The last help! Please~
Thanks for your kind contribution！

**Comment by askvortsov1** [comment]
You need to require v5.2.5 of minishlink web push

**Comment by Roy-Kid** [comment]
![image](https://user-images.githubusercontent.com/42854324/93910184-5174f400-fd33-11ea-98e7-0848e7343991.png)
After installing the v5.2.5 minishlink, there still a notification that tells me I have no gmp and minishlink. 
If it is not easy to solve, it ok. I can wait for the next version update
Thanks again for your generously help ！！！

**Comment by askvortsov1** [comment]
You're making progress! Now, you need to ensure that the php-gmp extension is not just installed, but also enabled. The exact steps for doing this depend on your server's operating system.
