### ISSUE TITLE
Opting in for Push Notifications throws an error on Firefox

### ISSUE THREAD

**Issue by iPurpl3x** [askvortsov1/flarum-pwa#11]
When using the option to activate push notifications on a new device 
<img width="851" alt="image" src="https://user-images.githubusercontent.com/18526076/95214665-6ac87680-07f0-11eb-9bc8-cab00b47aeae.png">
Then allowing notifications
<img width="386" alt="image" src="https://user-images.githubusercontent.com/18526076/95214707-774ccf00-07f0-11eb-938d-6e204ccbb6f6.png">
I get the following error : `Uncaught TypeError: can't access property "pushManager", app.sw is undefined`
<img width="626" alt="image" src="https://user-images.githubusercontent.com/18526076/95214857-9d726f00-07f0-11eb-96b7-b946ee47a7f4.png">

**Browser:** Firefox Developer Edition 82
**Flarum:** 0.1.0-beta.13
**askvortsov/flarum-pwa:** v1.0.7

**Comment by askvortsov1** [comment]
I just tried this on Firefox stable 82, and didn't see this issue. Possibly this was something on Firefox's end?

**Comment by iPurpl3x** [comment]
That must have been it. I got it working with the latest update! 

<img width="372" alt="image" src="https://user-images.githubusercontent.com/18526076/97054273-ce8ac780-1584-11eb-9791-782debeb9ecb.png">
