### ISSUE TITLE
Browser tab has broken when you click share link on dropdown menu in profile page

### ISSUE THREAD

**Issue by ayyilmaz** [askvortsov1/flarum-pwa#12]
I think there is a bug. My browser tab has broken when I click share link on dropdown menu in profile page.

![](https://i.ibb.co/nbGpS5D/broken.png)

![](https://i.ibb.co/7k2svxm/asdasd.jpg)

**Comment by askvortsov1** [comment]
Which browser is this? That option shouldn't be displayed when the browser doesn't support the share API

**Comment by askvortsov1** [comment]
Which version / OS? I wasn't able to replicate this locally

**Comment by ayyilmaz** [comment]
> Which version / OS? I wasn't able to replicate this locally

I use Windows 8.1 Industry Embedded. I use Google Chrome 86.0.4240.111 .

**Comment by askvortsov1** [comment]
Unfortunately this might be an OS incompatibility, not sure that I can do much about it.
