### ISSUE TITLE
PWA Name

### ISSUE THREAD

**Issue by lhunath** [askvortsov1/flarum-pwa#17]
Currently, the extension uses the forum's title as the "short name", ie. the name that appears as the app name.

This is fine as a default, but not fine as a general hard rule.  App names are generally very constrained strings and their usage is not in the least bit compatible with the usage of a web page title.

Interestingly, PWA does force you to enter a "longer name".  It actually makes a lot more sense for this one to be inherited from the forum's title than the short name.

Proposing that the extension allows the user to modify the short name and that both the long and short name default to the forum's title if not specified.

**Comment by askvortsov1** [comment]
Thank you very much! Fixed by merging #18
