### ISSUE TITLE
Push notification for a new post takes you to the first post in the discussion

### ISSUE THREAD

**Issue by rafaucau** [askvortsov1/flarum-pwa#27]
When I get a push notification of a new post in a discussion, when I click on it, instead of taking me to this new post, it takes me to the beginning of the discussion.

**Comment by askvortsov1** [comment]
I've released v3.0.4, is it better now? It should be linking to the post that triggered the notification.

**Comment by rafaucau** [comment]
@askvortsov1 It still works the same as before.
BTW. the content of the notification displays the content of the first post in the discussion instead of the post to which the notification applies

**Comment by rafaucau** [comment]
Now I noticed that it goes to the correct post if it is a notification that someone has replied to my post. But if it is a notification of a new post in a followed discussion it goes to the first post in the discussion.
