### ISSUE TITLE
Incorrect text when sharing - [Object Object]'s reply to [Object Object]

### ISSUE THREAD

**Issue by rafaucau** [askvortsov1/flarum-pwa#28]
![IMG_20210625_222746](https://user-images.githubusercontent.com/25438601/123482230-34908880-d605-11eb-8bfc-9d926891c64e.jpg)

**Comment by askvortsov1** [comment]
Could you try v3.0.5?

**Comment by rafaucau** [comment]
Now it works. Thanks
