### ISSUE TITLE
The content of a new post notification should include the content of this post, not the content of the first post in the discussion

### ISSUE THREAD

**Issue by rafaucau** [askvortsov1/flarum-pwa#36]
The content of a new post notification should include the content of this post, not the content of the first post in the discussion.
It would be more useful for users to have the content of the post they are notified about there.

**Comment by askvortsov1** [comment]
For `newPost` notifications from the subscriptions extension, this should already be the case. Which type of notification are you seeing issues with?

**Comment by rafaucau** [comment]
@askvortsov1 Ah, indeed. The problem is with push notifications from `fof/byobu`.

**Comment by askvortsov1** [comment]
Should be fixed in v3.1.3

**Comment by rafaucau** [comment]
Thanks!
