### ISSUE TITLE
Flarum 1.4.1 Plugin not available

### ISSUE THREAD

**Issue by hkyang233** [askvortsov1/flarum-pwa#40]
> Flarum1.4.1
> PHP7.4.28
> MySQL5.6.50-log
Hello, I have encountered a bug, how can I fix it.

{"errors":[{"status":"405","code":"method_not_allowed","detail":"Flarum\\Http\\Exception\\MethodNotAllowedException: GET in \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/ResolveRoute.php:60\nStack trace:\n#0 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\ResolveRoute-\u003Eprocess()\n#1 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/SetLocale.php(51): Laminas\\Stratigility\\Next-\u003Ehandle()\n#2 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\SetLocale-\u003Eprocess()\n#3 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/AuthenticateWithHeader.php(58): Laminas\\Stratigility\\Next-\u003Ehandle()\n#4 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\AuthenticateWithHeader-\u003Eprocess()\n#5 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/AuthenticateWithSession.php(31): Laminas\\Stratigility\\Next-\u003Ehandle()\n#6 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\AuthenticateWithSession-\u003Eprocess()\n#7 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/RememberFromCookie.php(52): Laminas\\Stratigility\\Next-\u003Ehandle()\n#8 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\RememberFromCookie-\u003Eprocess()\n#9 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/StartSession.php(61): Laminas\\Stratigility\\Next-\u003Ehandle()\n#10 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\StartSession-\u003Eprocess()\n#11 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Api\/Middleware\/FakeHttpMethods.php(29): Laminas\\Stratigility\\Next-\u003Ehandle()\n#12 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Api\\Middleware\\FakeHttpMethods-\u003Eprocess()\n#13 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/ParseJsonBody.php(28): Laminas\\Stratigility\\Next-\u003Ehandle()\n#14 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\ParseJsonBody-\u003Eprocess()\n#15 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/HandleErrors.php(57): Laminas\\Stratigility\\Next-\u003Ehandle()\n#16 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\HandleErrors-\u003Eprocess()\n#17 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/InjectActorReference.php(25): Laminas\\Stratigility\\Next-\u003Ehandle()\n#18 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\InjectActorReference-\u003Eprocess()\n#19 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/MiddlewarePipe.php(75): Laminas\\Stratigility\\Next-\u003Ehandle()\n#20 \/www\/wwwroot\/flarum\/vendor\/middlewares\/request-handler\/src\/RequestHandler.php(84): Laminas\\Stratigility\\MiddlewarePipe-\u003Eprocess()\n#21 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Middlewares\\RequestHandler-\u003Eprocess()\n#22 \/www\/wwwroot\/flarum\/vendor\/middlewares\/base-path-router\/src\/BasePathRouter.php(101): Laminas\\Stratigility\\Next-\u003Ehandle()\n#23 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Middlewares\\BasePathRouter-\u003Eprocess()\n#24 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Middleware\/OriginalMessages.php(36): Laminas\\Stratigility\\Next-\u003Ehandle()\n#25 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Laminas\\Stratigility\\Middleware\\OriginalMessages-\u003Eprocess()\n#26 \/www\/wwwroot\/flarum\/vendor\/middlewares\/base-path\/src\/BasePath.php(73): Laminas\\Stratigility\\Next-\u003Ehandle()\n#27 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Middlewares\\BasePath-\u003Eprocess()\n#28 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Middleware\/ProcessIp.php(24): Laminas\\Stratigility\\Next-\u003Ehandle()\n#29 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/Next.php(49): Flarum\\Http\\Middleware\\ProcessIp-\u003Eprocess()\n#30 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/MiddlewarePipe.php(75): Laminas\\Stratigility\\Next-\u003Ehandle()\n#31 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-stratigility\/src\/MiddlewarePipe.php(64): Laminas\\Stratigility\\MiddlewarePipe-\u003Eprocess()\n#32 \/www\/wwwroot\/flarum\/vendor\/laminas\/laminas-httphandlerrunner\/src\/RequestHandlerRunner.php(96): Laminas\\Stratigility\\MiddlewarePipe-\u003Ehandle()\n#33 \/www\/wwwroot\/flarum\/vendor\/flarum\/core\/src\/Http\/Server.php(44): Laminas\\HttpHandlerRunner\\RequestHandlerRunner-\u003Erun()\n#34 \/www\/wwwroot\/flarum\/public\/index.php(26): Flarum\\Http\\Server-\u003Elisten()\n#35 {main}"}]}

**Comment by pwFoo** [comment]
Is there a working push notification solution for flarum?
Searching or a forum with push notifications a long time.

Following here

**Comment by askvortsov1** [comment]
Doesn't seem to be related to this extension
