### ISSUE TITLE
Allow no color option (Theme and Background)

### ISSUE THREAD

**Issue by iamdarkle** [askvortsov1/flarum-pwa#41]
Currently you are forced to enter a Theme and Background color, if you were allowed to enter the "none" option the system colors would be preferred, which would be especially good for the Theme color as it would match the dark or light mode of the user's device.

**Comment by iamdarkle** [comment]
Just reviewing this previous issue, I have noticed that it seems that the color selection doesn't work, I mean whatever color you put, it seems that the main colors are selected, could someone confirm this?

**Comment by askvortsov1** [comment]
Should be fixed in new version.
