### ISSUE TITLE
Safari Resource Preload Issue

### ISSUE THREAD

**Issue by Clamours** [askvortsov1/flarum-pwa#55]
I found that this extension may cause
"The resource XXXX was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing"
warning on Safari browser, which This will cause a second refresh every time the user returns to the previous page.
Please help check this problem, thank you!
<img width="659" alt="QQ20240220-210057@2x" src="https://github.com/askvortsov1/flarum-pwa/assets/60908461/b2891a61-7669-4ac9-85cc-efb96d3ace99">

**Comment by DellZHackintosh** [comment]
It won't cause anything and they're not caused by this extension.
